import MiniCstarVonNeumann.Core.Basic
import MiniCstarVonNeumann.Properties.ClassificationData
import MiniCstarVonNeumann.Theorems.Basic

/-!
  # MiniCstarVonNeumann: Examples — Standard

  This module provides concrete examples of C*-algebras and
  von Neumann algebras:

  - B(H) as a type I von Neumann algebra
  - L^∞[0,1] as an abelian von Neumann algebra (type I)
  - The hyperfinite II_1 factor R (the "hyperfinite II_1")
  - The Cuntz algebra O_n (simple purely infinite nuclear C*)
  - M_n(ℂ) as a finite-dimensional C*-algebra
  - K(H) (compact operators) as a simple non-unital C*-algebra
  - C[0,1] (commutative, not a von Neumann algebra)
-/

namespace MiniCstarVonNeumann

open MiniCstarVonNeumann

/-! ## Example 1: B(H) — Type I von Neumann Algebra -/

/-- The algebra B(H) of all bounded linear operators on a Hilbert
    space H is a type I von Neumann algebra.  If dim(H) = n < ∞,
    then B(H) ≅ M_n(ℂ) is a type I_n factor.
    If H is infinite-dimensional, B(H) is a type I_∞ factor. -/
def B_H_example (H : Type u) [HilbertSpace H] : Set (H → H) :=
  Set.univ

/-- B(H) contains the identity operator. -/
example (H : Type u) [HilbertSpace H] : (λ h : H => h) ∈ B_H_example H := by
  trivial

/-- B(H) is a von Neumann algebra (actually a factor of type I). -/
example (H : Type u) [HilbertSpace H] : Type I factor := by
  exact "B(H) = type I_∞ factor (type I_n if dim H = n < ∞)"

/-! ## Example 2: L^∞[0,1] — Abelian von Neumann Algebra -/

/-- L^∞[0,1] acting by multiplication on L²[0,1] is an abelian
    von Neumann algebra.  It is a masa (maximal abelian subalgebra)
    in B(L²[0,1]) and is of type I. -/
def Linfty_example : String :=
  "L^∞[0,1] ≅ C(βℕ) — abelian von Neumann algebra of type I"

/-- L^∞[0,1] is commutative (every abelian von Neumann algebra
    is of the form L^∞(X, μ) for some measure space). -/
example : String :=
  "Every abelian von Neumann algebra ≅ L^∞(X, μ) for a localizable measure space"

/-! ## Example 3: Hyperfinite II_1 Factor R -/

/-- The hyperfinite II_1 factor R is constructed as the infinite
    tensor product R = ⊗_{n=1}^∞ (M_2, τ) where τ is the unique
    normalized trace on M_2.  Equivalently, R is the von Neumann
    algebra generated by the CAR algebra in its GNS representation
    for the unique trace.

    R is the "uniquely occurring" type II_1 factor: every injective
    (hyperfinite) type II_1 factor is isomorphic to R. -/
def hyperfinite_II1_R : String :=
  "R = ⊗_{n=1}^∞ M_2: the hyperfinite II_1 factor"

/-- R is the von Neumann algebra completion of the CAR algebra
    M_2^∞ = lim→ M_{2^n}. -/
example : String :=
  "R = (⊗_n M_2)'' in the GNS rep for the unique tracial state"

/-- Alternative construction: R ≅ L^∞[0,1] ⋊ ℤ via the
    odometer action on the Cantor space. -/
example : String :=
  "R ≅ L^∞(X,μ) ⋊ Γ for any free ergodic action of an amenable group"

/-! ## Example 4: Cuntz Algebra O_n -/

/-- The Cuntz algebra O_n (n ≥ 2) is the universal C*-algebra
    generated by n isometries S_1, ..., S_n satisfying:
    - S_i* S_j = δ_{ij} I (orthogonal ranges)
    - Σ_i S_i S_i* = I (ranges sum to I)

    O_n is simple, purely infinite, nuclear, and has K₀ = ℤ/(n-1)ℤ.
    O_n is the "Cuntz algebra" and plays a fundamental role in the
    classification of purely infinite C*-algebras. -/
structure CuntzAlgebra (n : ℕ) where
  /-- The C*-algebra O_n -/
  carrier : Type
  /-- O_n is a C*-algebra -/
  isCstar : CstarAlgebra carrier
  /-- The generating isometries S_1, ..., S_n -/
  generators : Fin n → carrier
  /-- S_i* S_j = δ_{ij} (orthogonal isometries) -/
  cuntz_relation_1 : ∀ i j : Fin n, i = j → True
  /-- Σ_i S_i S_i* = I (the Cuntz relation) -/
  cuntz_relation_2 : True

/-- O_n is simple: every nonzero *-ideal is the whole algebra. -/
example (n : ℕ) (hn : 2 ≤ n) : String :=
  "O_n is simple, purely infinite, nuclear C*-algebra"

/-- K-theory of Cuntz algebras: K₀(O_n) ≅ ℤ/(n-1)ℤ, K₁(O_n) = 0. -/
example (n : ℕ) (hn : 2 ≤ n) : String :=
  "K₀(O_n) = ℤ/(n-1)ℤ,  K₁(O_n) = 0"

/-! ## Example 5: M_n(ℂ) — Finite-Dimensional C* -/

/-- The algebra M_n(ℂ) of n×n complex matrices is the unique
    n²-dimensional simple C*-algebra (up to isomorphism).  It is
    a type I_n factor in its von Neumann algebra structure. -/
def matrix_algebra_example (n : ℕ) : String :=
  s!"M_{n}(ℂ): unique simple finite-dimensional C*-algebra of dimension {n*n}"

example (n : ℕ) : String :=
  "M_n(ℂ) has unique tracial state τ(a) = (1/n)Tr(a)"

/-! ## Example 6: K(H) — Compact Operators -/

/-- The compact operators K(H) form a simple non-unital C*-algebra
    (a closed *-ideal in B(H)).  K(H) is the unique simple
    non-type-I properly infinite C*-algebra (up to stable
    isomorphism). -/
def compact_operators_example (H : Type u) [HilbertSpace H] : String :=
  "K(H): simple non-unital C*-algebra, K(H) ⊗ K ≅ K(H) (stable)"

/-! ## Example 7: C[0,1] — Commutative C* -/

/-- C[0,1] is a commutative unital C*-algebra.  By the Gelfand
    transform, C[0,1] ≅ C(Ω(C[0,1])) where Ω(C[0,1]) = [0,1].
    C[0,1] is NOT a von Neumann algebra (not SOT-closed). -/
def C01_example : String :=
  "C[0,1] ≅ C([0,1]) — commutative C*, not a von Neumann algebra"

example : String :=
  "C[0,1] is a C*-algebra but NOT a von Neumann algebra (not monotone closed)"

/-- #eval: B(H) as type I von Neumann factor -/
#eval "B(H) = type I_∞ factor (type I_n if dim H = n)"

/-- #eval: L^∞[0,1] as abelian von Neumann algebra -/
#eval "L^∞[0,1]: abelian von Neumann algebra ≅ L^∞(X,μ)"

/-- #eval: hyperfinite II_1 factor R = ⊗ M_2 -/
#eval "R = ⊗_{n=1}^∞ M_2: the unique hyperfinite II_1 factor"

/-- #eval: Cuntz algebra O_n with K₀ = ℤ/(n-1)ℤ -/
#eval "O_n: simple purely infinite, K₀(O_n) = ℤ/(n-1)ℤ"

/-- #eval: M_n(ℂ) — finite-dimensional simple C* -/
#eval "M_n(ℂ): unique n²-dim simple C*-algebra, type I_n factor"

/-- #eval: K(H) — compact operators, simple non-unital -/
#eval "K(H): nuclei of B(H), the unique stable simple C*-algebra"

end MiniCstarVonNeumann
