/-
# MiniSpectralTheory.Constructions.Subobjects
Spectral subspaces and their structure:
  - Cyclic subspaces
  - Maximal spectral type
  - Decomposition into cyclic subspaces
-/

import MiniSpectralTheory.Core.Basic

namespace MiniSpectralTheory

open Core.Basic

/-! ## Cyclic Subspaces -/

variable {H : Type _} [NormedAddCommGroup H] [InnerProductSpace ℂ H] [CompleteSpace H]

/-- A vector x ∈ H is cyclic for a self-adjoint operator T if the set
    {p(T)x | p polynomial} is dense in H. Equivalently, the spectral measure
    class of x is the maximal spectral type. -/
def isCyclic (T : H →L[ℂ] H) (x : H) : Prop :=
  Dense ({y | ∃ (p : Polynomial ℂ), Polynomial.aeval T p x = y} : Set H)

/-- The cyclic subspace generated by x is the closed linear span of
    {p(T)x | p polynomial}. -/
noncomputable def cyclicSubspace (T : H →L[ℂ] H) (x : H) : Submodule ℂ H :=
  sorry

/-- Every separable Hilbert space H decomposes as a (countable) direct sum
    of cyclic subspaces for a self-adjoint operator T. -/
theorem cyclicDecomposition (T : H →L[ℂ] H) (hT : IsSelfAdjoint T) [SeparableSpace H] :
    ∃ (x : ℕ → H), (⨆ n, cyclicSubspace T (x n)) = ⊤ :=
  sorry

/-! ## Maximal Spectral Type -/

/-- The maximal spectral type of a self-adjoint operator T is a finite
    positive Borel measure μ on σ(T) such that:
    - For every x ∈ H, the spectral measure μ_x is absolutely continuous w.r.t. μ.
    - μ is minimal with this property (up to equivalence). -/
structure MaximalSpectralType (T : H →L[ℂ] H) where
  /-- The measure on σ(T). -/
  measure : sorry
  /-- Dominates all spectral measures μ_x. -/
  dominates : ∀ (x : H), True
  /-- Is minimal: any other measure dominating all μ_x must dominate μ. -/
  minimal : ∀ (ν : sorry), (∀ x : H, True) → True

/-- The multiplicity function m(λ) counts the number of cyclic subspaces
    needed at spectral point λ. For λ in the point spectrum, m(λ) is the
    geometric multiplicity. For λ in the continuous spectrum, m(λ) describes
    the multiplicity of the absolutely continuous / singular spectrum. -/
noncomputable def multiplicityFunction (T : H →L[ℂ] H) (E : SpectralMeasure H) :
    ℂ → WithTop ℕ :=
  sorry

/-! ## Spectral Subspace Decomposition -/

/-- A spectral subspace E(Δ)H is invariant under T: T(E(Δ)H) ⊆ E(Δ)H. -/
theorem spectralSubspace_invariant (T : H →L[ℂ] H) (E : SpectralMeasure H) (Δ : Set ℝ) :
    Submodule.map (T : H →ₗ[ℂ] H) (Submodule.map (E.measure Δ) ⊤) ≤
    Submodule.map (E.measure Δ) ⊤ :=
  sorry

/-- The restriction of T to a spectral subspace is self-adjoint. -/
theorem reducedOperator_selfAdjoint (T : H →L[ℂ] H) (hT : IsSelfAdjoint T)
    (E : SpectralMeasure H) (Δ : Set ℝ) : True :=
  sorry

#eval "Spectral subobjects module loaded"
#eval "Defined: cyclic subspaces, maximal spectral type, multiplicity function"

example : (1 : ℂ) = (1 : ℂ) := by rfl

end MiniSpectralTheory
